version: '3.8'
name: accounting-app

services:  
  webapi:
    build:
        context: ./backend/srcs/WebApi
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    networks:
        - accounting-app
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "5000:80"
      - "2525:25"
    networks:
      - accounting-app
    volumes:
      - ../data/smtp4dev-data:/app/data
    restart: unless-stopped
      
volumes:
  smtp4dev-data:

networks:
  accounting-app:
    driver: bridge